config/routes.rb
Rails.application.routes.draw do
  resources :characters, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end
  
  def show
    @character = Character.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<h1>Listing Characters</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
 
  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= link_to 'Show', character_path(character) %></td>
    </tr>
  <% end %>
</table>

app/views/characters/show.html.erb
<h1>Character</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
 
  <tr>
    <td><%= @character.name %></td>
    <td><%#= link_to 'Show', character_path(character) %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>